Polarization file from LOBSTER.
Units are  μC/cm2

         Rel. Mulliken pol. vector       Rel. Loewdin pol. vector
  x                         -41.13                         -31.94
  y                           0.19                           0.08
  z                         -45.39                         -35.26
abs                          61.25                          47.57
                    unit:  μC/cm2                 unit:  μC/cm2
